module.exports = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_SCOPE_INSUFFICIENT: 'TOKEN_SCOPE_INSUFFICIENT',

  // Resources
  CONFLICT: 'CONFLICT',
  GONE: 'GONE',
  TRANSFER_CONFIRMATION_REQUIRED: 'TRANSFER_CONFIRMATION_REQUIRED',

  // Upstream services
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  BAD_GATEWAY: 'BAD_GATEWAY',
};
